plgd-dev/go-coap

- blockwise.go
- blockwise_test.go
- responsewriter.go
- server.go
When responding to blockwise requests using `ResponseWrite.Write` the server would use the message ID of the first block message rather than the last. This meant that clients would fail to handle the response.
This was due to not creating a new response writer when we created a new request.
> Fix responding to blockwise requests using Write

- servermux.go
Letting panics leak through the package boundary should be the last resort solution. None of the servermux conditions that lead to panic are unrecoverable.
See:
- https://github.com/golang/go/wiki/CodeReviewComments#dont-panic
- https://golang.org/doc/effective_go.html#errors
- https://golang.org/doc/effective_go.html#panic
> Don't panic

- README.md
- error.go
- message.go
- message_test.go
- noresponsewriter.go
- noresponsewriter_test.go
- responsewriter.go
OptionID has to be made uint16 in order to support the no-response
option number i.e. 258.
Added Encoding and Decoding message tests for the no-response option.
Reference: https://tools.ietf.org/html/rfc7967
> support no-response option

- blockwise.go
- client_test.go
- error.go
- message.go
- message_test.go
- messagedgram.go
- messagetcp.go
- messagetcp_test.go
- networksession.go
- server.go
- server_test.go
- added `ToBytesLength()` and tests for `MessageBase` and `TCPMessage`  
- validate the `MaxMessageSize` for tcp session.
> validate MaxMessageSize in blockwise and tcp session

- net/connDTLS.go
I have used `go-coap` (commit 4d60089651dfdc4b0f0ff5011c121c53535dfd5b) in a DTLS setting and CPU usage spikes pretty soon on both macOS and Rasbian. After some investigation and profiling, I think I have found the issue to be a timeout calculation bug in the `net/connDTLS.go` file where a delay is computed by subtracting a deadline from a `time.Now` call. I assume the deadline should be sometime in the future most of the time and thus the result is often negative. Things look better to me if the order of the operands are changed.
With the provided fix, CPU usage is much more reasonable!
> Switch order of operands in DTLS timeout calculation

- message.go
- message_test.go
For options those are not defined by IETF, old implementation of the program is ignore them.  
Updated `parseOptionValue`  so we can get original value.  
related issue [https://github.com/go-ocf/go-coap/issues/71](71)
> surpport unkown options

- message.go
- message_test.go
For options those are not defined by IETF, old implementation of the program is ignore them.
Updated parseOptionValue so we can get original value.
related issue https://github.com/go-ocf/go-coap/issues/71
FYI: @duanxuelin
> Unknown option

- error.go
- net/dtlslistener.go
- net/error.go
- net/tcplistener.go
- net/tlslistener.go
- server.go
@jkralik 
Regarding issue https://github.com/go-ocf/go-coap/issues/67
The review has a lot of noise due to moving net package into coap.  The reason I did that was because I made use of error objects in error.go that's in the coap package and seems like it should be accessible as "coap.ErrServerClosed".  Similar to the golang http library "http.ErrServerClosed".  Let me know if you want to restructure a different way instead.
The important changes are in dtlslistener.go, tlslistener.go, tcplistener.go where it returns ErrServerClosed on the context.Done() channel on shutdown.  Then inside of the accept loops for DTLS, TCP, etc, inside of server.go, instead of returning on every error, we continue and only return when an ErrServerClosed error is encountered.
> ListenAndServe should only return on shutdown or fatal error

- message.go
Thank you for merging my previous pull request. In this pull request, I have added support to stringify CoAP options which was useful to me when I wanted to parse a CoAP message and print out the CoAP option name along with its value present within the message. Looking forward to your review and subsequent merge to master! 🙏
> add support to stringify coap options

- client.go
- clientcommander.go
- net/conn.go
- networksession.go
- request.go
- server.go
- sessiondtls.go
- sessiontcp.go
- sessionudp.go
This will, for example, allow the server to get the client certificate (chain) in case of DTLS.
The certificates can be accessed as `req.PeerCertificates` where `req` is of type `req *coap.Request`.
Fixes #103
@jkralik Could you please look at these changes? I'd love some feedback and am happy to change this in any way. The changes I've done now worked for me, but I'm not sure whether the way I've done these changes is preferred as I'm new to the codebase (and Go).
Some elements in specific I'm not sure about:
- In [net/conn.go](https://github.com/jdbruijn/go-coap/blob/bedcb6752729174f0306f22296298c4848a141fa/net/conn.go#L38) I'm exposing the `Conn`, which could be altered by the receiver if I'm not mistaken. Although the same goes for the `LocalAddr` and `RenoteAddr` functions, I'm not …
> feat(cert): add peer certificates to the incoming request

- dtls_test.go
- examples/dtls/server/main.go
- examples/mcast/server/main.go
- examples/observe/server/main.go
- examples/ping/server/main.go
- examples/simple/server/main.go
- go.sum
- keepalive_test.go
- net/dtlslistener.go
- server.go
- server_test.go
@jkralik As per issue #67, implemented callbacks into listeners to return back error messages on any failures.  Also fixed a bug where the DTLS accept loop would exit if a single session has a handshake failure
> Add callback for errors occurring from listeners and fix DTLS accept loop from exiting

- dtls/client_test.go
- udp/client/client.go
- udp/client/clientconn.go
- udp/client/clientconn_test.go
- udp/client_test.go
- udp/discover.go
- udp/message/error.go
- udp/message/getmid.go
- udp/message/message.go
- udp/message/message_test.go
- udp/message/type.go
- udp/server.go
iotivity-lite checks for duplicate message via MID so it can drop
request when app uses more clients then one. To avoid issue GetMID
needs to be global function.
> export message.GetMID() as global function

- message/options.go
The wrong index variable in the loop was used, potentially causing not enough bytes allocated for the next cycle of the mux options conversion.
> fix: use loop index to calculate used length of options

- tcp/session.go
- udp/client/clientconn.go
On 32-bit platforms (e.g. Raspberry Pi) it is caller's responsibility to arrange 64-bit alignment of `sync/atomic` operation parameters, see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG. This PR fixes `SIGSEGV: segmentation violation` errors on Raspberry Pi by moving struct members accessed using `sync/atomic` to the beginning of the struct where proper alignment is guaranteed by the runtime.
An example of SIGSEGV error that occurs without this fix:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b20]
goroutine 1 [running]:
runtime/internal/atomic.goXadd64(0x2066094, 0x1, 0x0, 0x10000, 0x10)
/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c …
```
> Fix SIGSEGV crashes on 32-bit platforms (e.g. Raspberry Pi)

- net/conn.go
- net/connUDP.go
- net/dtlslistener.go
- net/isTemporary.go
- net/tcplistener.go
- net/tlslistener.go
- net/tlslistener_test.go
When connection is closed during TLS handshake, it returns i/o timeout.
So we need to validate if timeout real occurs by set deadline,
otherwise infinite loop occurs.
> fix infinite loop caused by close connection during TLS handshake

- net/connUDP.go
- udp/client/clientconn.go
- udp/client/clientconn_test.go
- udp/client/mutexmap.go
- udp/client/mutexmap_test.go
Fixes #156
As described in RFC 7252 4.5. Message Deduplication
- Handlers are only called once per received message id
- Responses are cached for EXCHANGE_LIFETIME = 247s (due to RFC 7252)
- Parallel handling of the same message ID is avoided to ensure propper caching
- Removed redundant setting of message ID and Type in func (cc *ClientConn) do(...)
- Fixed an error formatting mistake in connUDP.go
> Deduplicate messages with the same message ID for UDP

- message/pool/message.go
- mux/message.go
- net/blockwise/blockwise.go
- net/blockwise/blockwise_test.go
- udp/client/clientconn.go
- udp/client/mux.go
- udp/client_test.go
- udp/message/pool/message.go
- udp/message/type.go
Fixes #191
- Non-confirmable requests are getting Non-confirmable responses by default
- Mux Message has IsConfirmable field for handler
- Blockwise transfer is keeping UDP message types
- ClientConn midHandlerContainer is only used for CON messages
- Non-confirmable requests are never re-transmitted
- The default type for new messages is Confirmable for backwards compatibility
- Added related testcases and asserts
> Allow client to send non-confirmable messages

- go.mod
- go.sum
- udp/client/clientconn.go
Fixes #180 
Adds SetTransmissionNStart, SetTransmissionAcknowledgeTimeout, SetTransmissionMaxRetransmit
It's not threadsafe, do we needs an additional Mutex and "safe" methods for using the values?
> Allow to set UDP ClientConn timing parameters

- dtls/client.go
- dtls/client_test.go
- dtls/options.go
- dtls/server.go
- dtls/server_test.go
- net/conn.go
- net/connUDP.go
- net/dtlslistener.go
- net/monitor/inactivity/inactivitymonitor.go
- net/options.go
- net/tcplistener.go
- net/tlslistener.go
- tcp/clientconn.go
- tcp/clientconn_test.go
- tcp/options.go
- tcp/server.go
- tcp/server_test.go
- tcp/session.go
- udp/client.go
- udp/client/clientconn.go
- udp/client_test.go
- udp/options.go
- udp/server.go
- udp/server_test.go
In old implementation it spawn go-routine per connection for check if the connection is inactive. Now it is handled directly by connection for DTLS/TCP. For udp it creates one goroutine which goes through all udp connections and check if they are inactive. 
added support inactivity monitor for clients
> Remove goroutine for inactive monitor

- net/blockwise/blockwise.go
If you observe a resource and the state change is too big for a single
packet, it will be sent blockwise. However, only the first block is
sent with the observe token, it is expected that clients will request
subsequent blocks by issuing a new request. Returning a response to
this new request would fail on the client due to ETags not matching,
despite no ETags being used. The failure error was:
received message doesn't contains ETAG but cached received message contains it([])
This patch ensures that the received message actually contains an
ETag, which fixes this issue.
> Fix an issue which prevents blockwise xfer working with observe

- .vscode/settings.json
- mux/client.go
- tcp/clientobserve.go
- tcp/clientobserve_test.go
- udp/client/clientobserve.go
- udp/client/clientobserve_test.go
when the client receives a notification without observing option, it
means that the resource doesn't support the observation.
- added a call to check if the observation is canceled `obs.Canceled`
- automatically clean up observation, so users don't need to call
`obs.Cancel`
> observation: handle state when the resource observation is not supported

- net/blockwise/blockwise.go
- no functional changes.
- moved the following logic to separate functions.  
-- handling observe response
-- fetching the received message from the cache
-- fetching the payload from the received message 
-- sending the response
- blockwise unit tests passed
could be better if we can bringdown the gocyclo index to 15. currently it is at 24.
> Improve gocyclo from 43 to 24 for blockwise processReceivedMessage

- dtls/session.go
- net/blockwise/blockwise.go
- net/connUDP.go
- net/connUDP_test.go
- net/options.go
- tcp/clientconn.go
- tcp/server_test.go
- udp/client/clientconn.go
- udp/client/clientobserve_test.go
- udp/discover.go
- udp/message/pool/message.go
- udp/server_test.go
- udp/session.go
* Add option to send multicast to an unspecified interface
Co-authored-by: Jozef Kralik <jojo.lwin@gmail.com>
> Extends multicast options

- mux/message.go
- mux/router.go
- mux/router_test.go
The `PathTemplate` (or route pattern) is quite useful in the middlewares, for example when you want to aggregate metrics by endpoint rather than by path.
Example use in `gorilla/mux`:
```go
// prometheusMiddleware implements mux.MiddlewareFunc.
func prometheusMiddleware(next http.Handler) http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
route := mux.CurrentRoute(r)
path, _ := route.GetPathTemplate()
timer := prometheus.NewTimer(httpDuration.WithLabelValues(path))
next.ServeHTTP(w, r)
timer.ObserveDuration()
})
}
```
https://www.robustperception.io/prometheus-middleware-for-gorilla-mux
> Add PathTemplate to RouteParams

- tcp/message/pool/message.go
- udp/message/pool/message.go
On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.
> fix atomic alignment on 32-bit platforms

- examples/observe/server/main.go
The observe server example uses the same buffer for both the content of
the Content-Format and the Observe option. This does work int he example
by accident, as the used Content-Format is 0 and, hence, is encoded with
a zero-length option value. If modified like this, the issue becomes
apparent:
```diff
diff --git a/examples/observe/server/main.go b/examples/observe/server/main.go
index 08664a6..6ab6119 100644
--- a/examples/observe/server/main.go
+++ b/examples/observe/server/main.go
@@ -30,10 +30,10 @@ func sendResponse(cc mux.Client, token []byte, subded time.Time, obs int64) erro
}
var opts message.Options
var buf []byte
-    opts, n, err := opts.SetContentFormat(buf, message.TextPlain)
+    opts, n, err := opts.SetContentFormat(buf, message.AppJSON)
if err == message.ErrTooSmall { …
```
> examples/observe/server: fix buf usage

- message/options.go
- message/options_test.go
> message: Implement Options.LocationPath() & Options.SetLocationPath()

- tcp/session.go
As the `sequence` field of the `Session` was not the first within the struct, on 32bit OS, `panic: unaligned 64-bit atomic operation` was thrown.
Placing it first within the struct fixes the bug.
> fix 64bit atomic alignment on the Session struct

- message/codes/code_string.go
- message/codes/codes.go
We recently needed to add this constant locally to our CoAP server, but figured it be good to contribute it upstream as well. I wasn't sure about which uint to assign to it, hence the randomly chosen `145`. Happy to change it to something more appropriate.
> add TooManyRequests constant to support RFC-8516

- message/options.go
Signed-off-by: aryan <aryangodara03@gmail.com>
With reference to issue #384
> fix comment on function SetObserve

- net/blockwise/blockwise.go
Hello!
While using this lib I discovered that observe requests sometimes wasn't retried properly ([here](https://github.com/plgd-dev/go-coap/blob/e59fa916285a183e0adbcbf6d0c2e1329ddc448e/udp/client/clientconn.go#L258)). After a bit of digging I found out that messages coming from the message pool always are set to non-confirmable while new messages not coming from the pool are confirmable by default.
Since the blockwise code copies messages it can end up sending a non-confirmable message when the original message was actually set as confirmable.
I am not very familiar with this code base so I am not sure this fix is good, I have tested it with our server and it seems to solve the issue.
To me it feels wrong to assume what the type should be, so I guess it needs to be set every time a …
> Fix for messages coming from the message pool always ends up as non-confirmable

- net/blockwise/blockwise.go
Steps to reproduce:
1. Run a server for example on port 5688
2. Using coap client (https://libcoap.net/doc/reference/4.2.0/man_coap-client.html) run a request with giving block size, ex:
`coap-client -T token -b 16 -v 9 -m get 'coap://localhost:5688/a'`
Actual result:
Server ignores the Block2 option of 16 and returned whole response in single block as default server config is 1024 bytes SZX and this maxSZX from server is used instead of suggested size from client.
Expected result:
There should be multiple blocks with single block containing max 16 characters of transferred content as specified with flag "-b 16".
> fix returned block size in blockwise transfer

- .golangci.yml
- dtls/server/server.go
- dtls/server/session.go
- message/encodeDecodeUint32.go
- message/getmid.go
- message/noresponse/noresponse_test.go
- message/option.go
- message/options.go
- message/pool/message_test.go
- message/pool/pool.go
- net/blockwise/blockwise.go
- net/connUDP.go
- pkg/runner/periodic/periodic.go
- tcp/client/session.go
- tcp/coder/coder.go
- tcp/server/server.go
- tcp/server_test.go
- udp/client.go
- udp/client/clientconn.go
- udp/server/server.go
- udp/server/session.go
Removed linters:
- deadcode (obsolete)
- varcheck (obsolete)
Enabled linters:
- forcetypeassert
- gocritic
- gocyclo
- gomoddirectives
- gomodguard
- nilerr
- revive
- unparam
> Update linters and fix reported issues

- message/pool/message.go
There are two off-by-one errors in the upsert functions for message ID and message type.
`UpsertMessageId` should allow a value of 65535, while `UpsertType` should allow 255.
This fixes it, but I suspect it might break some tests or other things that rely on the existence of this bug (haven't tested). 
However, without this fix, a device sending a confirmable message to the server will recieve an ACK message back with an incorrect Message ID.
> Fix off-by-one error in upserts

- message/pool/message.go
- net/blockwise/blockwise.go
- net/blockwise/blockwise_test.go
- net/responsewriter/responseWriter.go
Because cached messages are released when "do" operations end and incoming responses are processed simultaneously, a race may occur.
```log
==================
WARNING: DATA RACE
Read at 0x00c000401054 by goroutine 281:
github.com/plgd-dev/go-coap/v3/message/pool.(*Message).Type()
/home/jkralik/go/pkg/mod/github.com/plgd-dev/go-coap/v3@v3.1.0/message/pool/message.go:109 +0x46
github.com/plgd-dev/go-coap/v3/net/blockwise.(*BlockWise[...]).getSentRequest()
/home/jkralik/go/pkg/mod/github.com/plgd-dev/go-coap/v3@v3.1.0/net/blockwise/blockwise.go:572 +0x43c
github.com/plgd-dev/go-coap/v3/net/blockwise.(*BlockWise[...]).processReceivedMessage()
/home/jkralik/go/pkg/mod/github.com/plgd-dev/go-coap/v3@v3.1.0/net/blockwise/blockwise.go:756 +0x951 …
```
> blockwise transfer: fix race

- message/option.go
#94 seems to be disappeared, so re-creating PR.
Additionally, adding LwM2M CBOR (`application/vnd.oma.lwm2m+cbor`) and SenML-ETCH JSON/CBOR (`application/senml-etch+json` / `application/senml-etch+cbor`) for [LwM2M 1.2](https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-74-3-Additional-IANA-registered-Media-Type-supported-in-LwM2M-TS-12).
<https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats>
> add media types

- udp/client/conn.go
- udp/server_test.go
To prevent collisions during reconnections, it is important to always increment the global counter. For example, if a connection (cc) is established and later closed due to inactivity, a new cc may be created shortly after. However, if the new cc is initialized with the same message ID as the previous one, the receiver may mistakenly treat the incoming message as a duplicate and discard it. Hence, by incrementing the global counter, we can ensure unique message IDs and avoid such issues.
> dtls/udp: ensure unique message IDs during reconnections

- net/observation/handler.go
- tcp/clientobserve_test.go
This commit introduces an enhancement to the observation mechanism in the network module by implementing ETag tracking. The latest ETag value associated with each observation is now stored in the internal representation.
With this update, each incoming message containing the ETag CoAP option automatically updates the ETag value for the relevant observation. When an observation is canceled, the stored ETag value is utilized. When the server detects a valid ETag match, it now responds with a VALID code and an empty payload instead of resending the content of the resource. This optimization minimizes unnecessary data transfer and reduces network load.
> net: Enhance observation management with ETag tracking

- examples/options/server/main.go
- server.go
1. Add public functions `ListenAndServeWithOptions`, `ListenAndServeTCPTLSWithOptions`, and `ListenAndServeDTLSWithOptions`. 
2. Add example code for an option server.
I cannot simply add options to the server, so I implemented this function as shown above.
I hope this is helpful!
> feature: add listen and serve with option function

- net/blockwise/blockwise.go
- net/observation/handler.go
Upon the commencement of the observation, the client has the ability to include ETAGs options within the GET request utilizing the observe option. Subsequently, on the server side, a Valid status code can be returned if any of the provided ETAGs are found to be a match.
> Fix processing of observe notifications with ETags

- dtls/server/session.go
Updates docstring on session.Run to indicate that it reads from the connection until closed.
> Fix description of session.Run

- message/option.go
Updates the text/plain media type string to use a space between the semicolon and the encoding. While this is not strictly required, it more closely aligns with the media types in the content format registry.
https://www.iana.org/assignments/core-parameters/core-parameters.xhtml
> Include whitespace between semicolon and encoding

- dtls/server/server.go
Updates the DTLS server to skip serving a DTLS connection when an error is returned. Previously, if an error was returned that did not meet the criteria of shutting down the server altogether, a non-nil DTLS connection would still attempt to be served. This can cause a panic if the net.Conn interface is non-nil, but the underlying value is.
Fixes #488
> fix: do not attempt serve DTLS connection on accept error

- udp/server_test.go
Interfaces must be up and running to be able to transport even loopback multicast. Without this one (or more) of the TestServerDiscovery tests might fail.
`
go test ./...
...
2023/10/17 11:41:55 ifs:[{1 65536 lo  up|loopback|running} {2 1500 enp1s0f0 ...
2023/10/17 11:41:55 first available multicast if:{2 1500 enp1s0f0 xx:xx:xx:xx:xx:xx  up|broadcast|multicast}
--- FAIL: TestServerDiscover (1.50s)
--- FAIL: TestServerDiscover/valid_first_interface (0.50s)
server_test.go:199: 
Error Trace:    /home/henning.rogge/develop/fkie-apps/go-coap/udp/server_test.go:199
Error:          "0" is not greater than "0"
Test:           TestServerDiscover/valid_first_interface
2023/10/17 11:42:04 inactivityMonitor
2023/10/17 11:42:04 inactivityMonitor
FAIL
FAIL    github.com/plgd-dev/go-coap/v3/udp …
> Interface must be UP and RUNNING for testing

- mux/router.go
The user should be able to use its own error handler for the mux router. In addition to this the mux should not silently log an error if the API user provides a bad path pattern.
> Improve mux errors

- mux/router.go
- mux/router_test.go
Mux router has trouble with root path matching because of the different semantics of empty path and "/" path. Add the already existing filter into all relevant router functions and add extend test cases to check all combinations.
> mux: filter for invalid root path pattern

- mux/router.go
mux/Router.GetRoutes() leaks access to the (lock-protected) internal map of the router. Clone the map before returning it to the user.
> Clone router map before returning it to user

- mux/router.go
- udp/server_test.go
This modification ensures that the mux treats both "/" and an empty path ("") as requests to the root path. The reason behind this is the absence of the Uri-path option in CoAP requests in such instances.
Fixes #446
> mux: Root path handling improvement

- .github/workflows/cifuzz.yml
- message/codes/codes.go
- message/codes/codes_test.go
Try fix Issue 61477 reported by libFuzzer in OSS-Fuzz
> Update UnmarshalJSON in codes package

- dtls/client.go
- dtls/server/config.go
- dtls/server/server.go
- message/message.go
- message/message_internal_test.go
- message/pool/message.go
- options/commonOptions.go
- tcp/client.go
- tcp/client/config.go
- tcp/client/conn.go
- tcp/client/session.go
- tcp/client_test.go
- tcp/server/config.go
- tcp/server/server.go
- udp/client.go
- udp/client/config.go
- udp/client/conn.go
- udp/client/conn_test.go
- udp/server/config.go
- udp/server/server.go
This pull request introduces a new feature to the CoAP connection module - Request Monitoring. The `WithRequestMonitor` function has been implemented to enable request monitoring for the connection. This function is called for each CoAP message received from the peer before it is processed.
Details of the Feature:
- **Functionality:** `WithRequestMonitor` allows developers to implement custom request monitoring logic for incoming CoAP messages.
- **Error Handling:** If the function returns an error, the connection is closed, providing a mechanism to handle and respond to issues in the monitoring process.
- **Message Dropping:** If the function returns true, the incoming message is dropped, allowing for selective handling or filtering of messages based on monitoring criteria.
This new …
> Add Request Monitoring Feature to CoAP Connection

- message/pool/message.go
- message/pool/message_test.go
Previously, the connection was being closed due to unmarshaling failures when more than 16 options were included in the message. This fix addresses the issue by increasing the buffer size to accommodate a higher number of options.
> Enhance Options Buffer for >16 Message Unmarshaling

- server.go
This change ensures that when a UDP option is provided in the options list, it is appropriately added to both the TCP and UDP option slices, ensuring consistent behavior for both server types.
#526
> Fix UDP Server Option Duplication in ListenAndServeWithOptions
