plgd-dev/go-coap

- README.md
- client.go
- client_test.go
- conn.go
- error.go
- examples/observe/client/main.go
- examples/observe/server/main.go
- examples/simple/client/main.go
- examples/simple/server/main.go
- message.go
- messagedgram.go
- messagetcp.go
- server.go
- server_test.go
- servermux.go
- session.go
- udp.go
add Exchange to Session for challenging client
add DefaultHandle to set default handler of mux
use same code of Server as for Client connection
session and client has similar interface
> refactoring: client uses same code server

- client.go
- conn.go
- message.go
- server.go
- server_test.go
- session.go
fixes for able to set Server.CreateSessionTCPFunc.
> publish Conn interface

- .gitignore
- .travis.yml
- README.md
- client.go
- client_test.go
- error.go
- examples/mcast/client/main.go
- examples/mcast/server/main.go
- server.go
- server_test.go
- udp.go
added option "udp[4-6]*-mcast" as network. To set a multicast
interfaces set server.UDPMcastInterfaces.
> add feature multicast

- README.md
No further comment needed I guess :wink:
> Fix reference to RFC7959

- message.go
- message_test.go
This PR contains the code for [issue-47](https://github.com/go-ocf/go-coap/issues/47).
> Setter for coap code for message

- go.mod
- go.sum
Resolves issue https://github.com/go-ocf/go-coap/issues/69
> update for dtls 1.5.4

- dtls_test.go
- go.mod
- go.sum
> Upd dtl sv1.5.4

- message.go
Thank you for creating and maintaining this great library!
I have added support for SenML JSON & SenML CBOR Media Types.
Looking forward to your review!
> add support for senml json & senml cbor

- README.md
This is mainly about how the tests can be run locally.
> docs: add contributing section to readme

- README.md
@jkralik Missed updating the README.md with the interface changes
> Update documentation to reflect new ListenAndServe interfaces

- dtls/server_test.go
- dtls/session.go
- tcp/server_test.go
- tcp/session.go
- udp/server.go
- udp/server_test.go
- udp/session.go
- addOnClose addOnRun with mutex
- handle ctx.Done in udp client/server
> fix of close sessions

- tcp/clientobserve.go
- udp/client/clientobserve.go
at first unblock Observe function and then call observeFunc
> fix of order calls in observation

- dtls/client.go
- dtls/options.go
- dtls/server.go
- dtls/session.go
- net/dtlslistener.go
- tcp/clientconn.go
- tcp/options.go
- tcp/server.go
- tcp/session.go
- udp/client.go
- udp/options.go
- udp/server.go
- udp/session.go
> fix of close underline socket

- net/observation/observation.go
- net/observation/observation_test.go
- tcp/clientobserve.go
- udp/client/clientobserve.go
fixes #179
implemented according to https://tools.ietf.org/html/rfc7641#section-3.4
> fix of silently stop notifications

- udp/client_test.go
Fixed #157
The issue was fixed somewhere already. I added a Test that fails with Tag v2.0.4 but works now, to ensure it stays fixed in future.
> Test that issue #157 is fixed

- dtls/client.go
- dtls/server.go
- tcp/clientconn.go
- tcp/server.go
- tcp/session.go
- udp/client.go
- udp/client/clientconn_test.go
- udp/server.go
add remote address and package name to error logs
> tcp: handle pong in connection goroutine

- net/blockwise/blockwise.go
> BWT: fix segfault for access to nil body message

- dtls/session.go
- net/conn.go
- tcp/session.go
https://github.com/golang/go/issues/31224
> properly set deadline during TLS handshake

- udp/discover.go
* udp/server: allow discover device by unicast
* add comment
> udp/server: allow discover device by unicast (#237)

- go.mod
- go.sum
- message/pool/message.go
- net/blockwise/blockwise.go
- net/blockwise/blockwise_test.go
- net/blockwise/senderRequestMap.go
- only one request can be performed via BWT - the request is determined by (COMMAND, href and query params)
> net/blockwise: parallel request is not supported by RFC

- dtls/server.go
- message/option.go
- message/options.go
- mux/middleware.go
- net/dtlslistener.go
- tcp/clientconn.go
- tcp/clientobserve.go
- udp/server.go
hey, was able to make use of linters to fix some code there by improving the readability a bit. 
imo, these changes shouldn't have functional or performance impact.
> Remove unused vars and improve code readability

- README.md
Wait for goreport card to support v2 or later major versions
(issue #369 to be fixed in the goreportcard repository).
> Disable goreportcard badge

- net/blockwise/blockwise.go
> Revert "Improve gocyclo from 43 to 24 for blockwise processReceivedMessage"

- udp/client/clientconn.go
According to RFC7252 5.2.1 Responses can
be sent piggybacked to the Acknowledgement.
The note states, that "there is a strong
expectation that servers will implement
code to piggyback whenever possible".
> udp/server: support piggyback response

- dtls/client.go
- dtls/server.go
- net/options.go
- udp/client.go
> remove unused heartBeat param

- message/options.go
This is a no-brainer change to get the linter happy
> messages/options.go: Make linter happy

- net/blockwise/blockwise.go
Hi,
This is https://github.com/plgd-dev/go-coap/pull/366 but for the v3 branch.
> Set type for messages coming from the message pool

- .golangci.yml
- go.mod
- go.sum
- message/getmid.go
- net/blockwise/blockwise_test.go
- pkg/rand/rand.go
- test/net/uri.go
Direct:
github.com/pion/udp v0.1.2
golang.org/x/exp v0.0.0-20230131160201-f062dba9d201
Indirect:
github.com/hashicorp/errwrap v1.1.0
> Upgrade dependencies

- message/bench_test.go
- message/options_test.go
- tcp/coder/bench_test.go
- tcp/coder/coder_test.go
- udp/client/bench_test.go
- udp/client/mutexmap_test.go
- udp/coder/bench_test.go
- udp/coder/coder_test.go
Fix error : https://github.com/plgd-dev/go-coap/pull/461#issuecomment-1649896922
Remove this : https://github.com/google/oss-fuzz/pull/10746/files#diff-a58053e99b85b52f948743b4e2a8c89937da814be3a8889eea3e45335fe62990R20-R23
> [Fuzzing] Fix oss-fuzz build and use a different file for benchmark testing

- .github/workflows/cifuzz.yml
Adding [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration) in workflows.
> [Fuzzing] add cifuzz
